/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_test;

import java_test.Greeter;
import java_test.gui;
import apsc143.*;

public class App {

    public static void main(String[] args) {
        Greeter greeter = new Greeter();
        System.out.println(greeter.Hello());
        System.out.println("Running GUI");
        java_test.gui.main(args);
        //assign3.main();
    }
}
