// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOfn8HUQ62DJ1ftO6eRpMMA34gaDdAVJI',
    appId: '1:696992576260:web:681b7995ea34df3f37d651',
    messagingSenderId: '696992576260',
    projectId: 'down-to-hang-8287f',
    authDomain: 'down-to-hang-8287f.firebaseapp.com',
    storageBucket: 'down-to-hang-8287f.appspot.com',
    measurementId: 'G-MS2JRZEBM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKmDxR4LBDybUQPayEfKF7_0PesMy_qyI',
    appId: '1:696992576260:android:3c1802d95f75a75a37d651',
    messagingSenderId: '696992576260',
    projectId: 'down-to-hang-8287f',
    storageBucket: 'down-to-hang-8287f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByYuaIEeP4fKEvQfDj7N8BSbbNKzjH-yc',
    appId: '1:696992576260:ios:36e2cbddea4aa51737d651',
    messagingSenderId: '696992576260',
    projectId: 'down-to-hang-8287f',
    storageBucket: 'down-to-hang-8287f.appspot.com',
    iosBundleId: 'com.example.flutterAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByYuaIEeP4fKEvQfDj7N8BSbbNKzjH-yc',
    appId: '1:696992576260:ios:07703129fd6465ae37d651',
    messagingSenderId: '696992576260',
    projectId: 'down-to-hang-8287f',
    storageBucket: 'down-to-hang-8287f.appspot.com',
    iosBundleId: 'com.example.flutterAuthentication.RunnerTests',
  );
}
